<Gerenciador>:
    Menu:
        name: 'menu'
    Comecar:
        name: 'comecar'
    Configuracoes:
        name: 'configuracoes'
    Votacao:
        name: 'votacao'
    Resultado:
        name: 'resultado'
<Menu>:
    BoxLayout:
        padding: '30sp'
        spacing: '30sp'
        orientation: 'vertical'
        Button:
            text: 'começar'
            on_release: root.configuracoes()
        Button:
            text: 'Sair'
            on_release: root.confirmacao()
<Configuracoes>:
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Configurações'
                    on_release: app.root.current = 'menu'
                ActionButton:
                    text: 'Sair'
                    on_release: app.root.get_screen('menu').confirmacao()
        ScrollView:
            BoxLayout:
                padding: 50
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'
                BoxLayout:
                    size_hint_y: None
                    height: 400
                    padding: 50
                    orientation: 'vertical'
                    Label:
                        id: label3
                        font_size: '50sp'
                        text: root.m
                    BoxLayout:
                        Button:
                            text: '+'
                            on_release: root.adicionar()
                        Button:
                            text: '-'
                            on_release: root.diminuir()
                BoxLayout:
                    padding: 50
                    size_hint_y: None
                    height: 400
                    orientation: 'vertical'
                    Label:
                        id: label2
                        font_size: '50sp'
                        text: root.m2
                    BoxLayout:
                        Button:
                            text: '+'
                            on_release: root.adicionar2()
                        Button:
                            text: '-'
                            on_release: root.diminuir2()
                BoxLayout:
                    padding: 50
                    size_hint_y: None
                    height: 200
                    orientation: 'vertical'
                    Button:
                        text: 'Começar'
                        on_release: app.root.get_screen('menu').menu()

<Comecar>:
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Começar'
                    on_release: app.root.get_screen('comecar').comecar()
                ActionButton:
                    text: 'Sair'
                    on_release: app.root.get_screen('menu').confirmacao()
        BoxLayout:
            padding: '200dp'
            spacing: '40dp'
            orientation: 'vertical'
            Label:
                id: label
                font_size: '50sp'

<Votacao>:
    ScrollView:
        BoxLayout:
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            Button:
                size_hint_y: None
                height: 200
                text: '1'
                on_release: root.votacao()
                on_release: root.b1()
            Button:
                size_hint_y: None
                height: 200
                text: '2'
                on_release: root.b2()

            Button:
                size_hint_y: None
                height: 200
                text: '3'
                on_release: root.votacao()
                on_release: root.b3()
            Button:
                size_hint_y: None
                height: 200
                text: '4'
                on_release: root.votacao()
                on_release: root.b4()
            Button:
                size_hint_y: None
                height: 200
                text: '5'
                on_release: root.votacao()
                on_release: root.b5()
            Button:
                size_hint_y: None
                height: 200
                text: '6'
                on_release: root.votacao()
                on_release: root.b6()
            Button:
                size_hint_y: None
                height: 200
                text: '7'
                on_release: root.votacao()
                on_release: root.b7()
            Button:
                size_hint_y: None
                height: 200
                text: '8'
                on_release: root.votacao()
                on_release: root.b8()
            Button:
                size_hint_y: None
                height: 200
                text: '9'
                on_release: root.votacao()
                on_release: root.b9()
            Button:
                size_hint_y: None
                height: 200
                text: '10'
                on_release: root.votacao()
                on_release: root.b10()
<Resultado>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50
        Label:
            text: f'resultado: {root.media}'
            font_size: '50sp'
        Button:
            text: 'Voltar para o menu'
            on_release: app.root.current = 'menu'
        Button:
            text: 'Reiniciar'
            on_release: app.root.get_screen('menu').menu()
